### ISSUE TITLE
Code style question: null check and assignment

### ISSUE THREAD

**Issue by webmaster128** [dropbox/nn#8]
After using nn in our project, I now have some places where I need to check a shared_ptr for null and conditionally assign it to nn_shared_ptr, e.g.

```c++
std::shared_ptr resultNullable = methodReturningNullOnError();
if (resultNullable) {
    auto result = NN_CHECK_ASSERT(resultNullable);
    // go on with `result`
}
```

Is there a way to rewrite this without the extra variable `resultNullable`?

In Swift there is the [if let](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/OptionalChaining.html) construct built into the language, that does null check and assignment in one step. Can something like this be done in an elegant way on the caller side?

**Comment by artwyman** [comment]
I don't think there's a way to do that in C++ without a variable (or hiding the variable inside of a macro or function or some other such trick).

`if let` in Swift seems useful.  I just looked at the example in this doc: https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/OptionalChaining.html

```
if let roomCount = john.residence?.numberOfRooms {
    print("John's residence has \(roomCount) room(s).")
} else {
    print("Unable to retrieve the number of rooms.")
}
```

I don't think it would exactly solve this problem either, though.  C++ does allow a similar pattern (at least in clang, which I just tried):

```
int test(int *x) {
    if (int * i = x) {
        return *i;
    }
    return -1;
}
```

I think the difference is that in the C++ example, the variable inside the `if` is of a nullable type, but guaranteed not to be null inside the if.  If you want to declare a variable of a type like nn<> which is non-nullable, there is no suitable value for that variable when the if is false, so you have to do the check before declaring the variable, not after.  I don't know enough about how Swift handles nullability to know if the implied type of `roomCount` is nullable at the type level or not.

**Comment by webmaster128** [comment]
In Swift, you can have enums with associated values to each enum value. An optional is an enum like this (from [A Swift Tour](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/GuidedTour.html)):

```swift
// Reimplement the Swift standard library's optional type
enum OptionalValue<Wrapped> {
    case none
    case some(Wrapped)
}
var possibleInteger: OptionalValue<Int> = .none
possibleInteger = .some(100)
```

Associated enum values as well as the built-in language feature `if let` cannot be ported directly to C++ I guess.

------------------

I now tried a lot of things to work around that limitation including a macro building a for loop with a nn in the body. But none of those tries looked promising enough to justify the massive hacking.

It's really sad that if the if statement can only take an assignment **or** an expression, making something like this impossible:

```c++
if (shared_pointer && auto nn = NN_CHECK_ASSERT(shared_pointer)) { ... }
```

I'm thinking of two possibilities to solve the issue: 1. have a wrapper type that implements `operator bool()`, allowing code like

```c++
if (auto result = NN_IS_NONULL(shared_pointer)) {
    auto nn = result.some_getter_returning_nn_type();
}
```

this limits the overhead to a method call and is better readable. The inverted test looks like

```c++
auto result = NN_IS_NONULL(shared_pointer)
if (!result) {
    // error out
}
auto nn = result.some_getter_returning_nn_type();
```

(which is not really better than the way by foot).

The 2. possibility would be the macro terror, doing something like

```c++
#define ifNonNull(expression, varname, block) \
    if (auto nullablePointer = expression) { auto varname = NN_CHECK_ASSERT(nullablePointer); block }

ifNonNull(shared_pointer, nn_var_name, {
    // use non-nullable `nn_var_name`
});
```

I tried to avoid lamda functions because the scope of the `return` keyword changes, which I think is usefull to have in the caller's scope.

At the end of the day, I am not really happy with the possibilities but maybe someone has additional thoughts.

**Comment by artwyman** [comment]
I don't see any better options, unfortunately.  I'm not a fan of macros which add what look like new language constructs, because it makes code harder to understand for outsiders.

I'm not sure I understand the first example for your option 1.  Your proposed type which has a `operator bool()` and can be converted to `nn_shared_pointer` sounds like it's just `shared_ptr` (other than a different syntax for how you do the conversion).

**Comment by webmaster128** [comment]
You're right, the first option has no real advantage over writing

```c++
if (std::shared_ptr resultNullable = methodReturningNullOnError()) {
    auto result = NN_CHECK_ASSERT(resultNullable);
    // go on with `result`
}
```

Well, okay than. Thanks for confirming that I did not miss any obvious fancy trick. Closing, as I assume there is nothing to add here.
